language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
cache:
  directories:
    - $HOME/.m2
before_install:
  # See: https://github.com/travis-ci/travis-ci/issues/2496
  - ulimit -t 514029
  # Required for HDFS tests (FLUME-2474)
  - umask 0022
