language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
env:
  - MAVEN_OPTS=""
  - MAVEN_OPTS="-Dhadoop.profile=1"
  - MAVEN_OPTS="-Dhadoop.profile=2-hbase-94"
cache:
  directories:
    - $HOME/.m2
before_install:
  # See: https://github.com/travis-ci/travis-ci/issues/2496
  - ulimit -t 514029
  # Required for HDFS tests (FLUME-2474)
  - umask 0022
  # HBase tests require that hostname points to 127.0.0.1
  - sudo sed -i -e 's~^127.0.1.1\(.*\)~127.0.0.1\1~g' /etc/hosts
